### ISSUE TITLE
Elvis works strangely in tmux.

### ISSUE THREAD

**Issue by ryanpcmcquen** [mbert/elvis#15]
Elvis does not display the entire file, I have to scroll through the file to display it line-by-line, this becomes extra confusing when you switch from downward to upward movement, a screenshot probably helps:

![screenshot_2015-12-30_16 11 34 522](https://cloud.githubusercontent.com/assets/772937/12059447/155519b2-af10-11e5-84f4-4ab8d87232f7.png)

**Comment by mbert** [comment]
Looks like a TERM problem. On Unix systems, Elvis uses the system's termcap interface. If your TERM environment variable points to something that is broken, Elvis will not work properly. You might get away by setting TERM to some other value. 

Elvis' termcap code is rather old and well-tested. I tend to believe that this problem is caused by system setup rather than by a bug in Elvis.

**Comment by ryanpcmcquen** [comment]
Nice, got around it with this:

https://github.com/ryanpcmcquen/linuxTweaks/blob/master/slackware/normal/.bash_profile#L59-L62

```shell
## fix elvis in tmux
alias elvis='TERM=xterm elvis'
alias vi='TERM=xterm elvis'
alias ex='TERM=xterm elvis'
```
