### ISSUE TITLE
can't load font *-courier-medium-r-*-18-*

### ISSUE THREAD

**Issue by dodona2** [mbert/elvis#28]
tried invoking elvis after regular build ./configure && make && make install:

can't load font *-courier-medium-r-*-18-*
no such window

**Comment by mbert** [comment]
When you run elvis with default settings, it will open the X11 interface if it detects an X11 environment. To enforce the text interface, you can use the '-G termcap' switch from the command line.

The X11 interface does not work on your system because the default font is not available on it. This can be remedied by editing elvis.ini (in /usr/local/share/elvis) or create a configuration in your HOME in which you change the standard fonts to something you have available on your system.
