### ISSUE TITLE
Elvis is vulnerable to CVE-2019-12735

### ISSUE THREAD

**Issue by TheLancashireman** [mbert/elvis#29]
Elvis can be used to execute arbitrary code simply by editing a downloaded text file.

https://github.com/numirias/security/blob/master/doc/2019-06-04_ace-vim-neovim.md

The exploit describes vim, but works in elvis too.

The patch for the documented PoCs seems to be quite simple - just ignore modelines that start with !
However, there might be other ways to execute code, such as piping part of the file through a command (e.g. :1,$!some_command)

**Comment by mbert** [comment]
Thank you for reporting. I will have to look into this at some time, but most likely not soon. If anybody wants to volunteer I shall happily review any PRs :)

**Comment by mbert** [comment]
BTW, the buffer to make the POC work, would have to look like this for Elvis:

```
ex::!uname -a||" vi:fen:fdm=expr:fde=assert_fails("source\!\ \%"):fdl=0:fdt=":
```

Most likely the problem could be fixed using some RX black magic in `elvis.arf`.

**Comment by mbert** [comment]
It turned out to be simpler than I thought. Please go ahead with some testing. 
The solution is simply filtering out any '!' from modeline lines before executing them. I would not rule out there are legitimate uses for '!' in modelines which this might break, but better safe than sorry. I don't consider "modeline" a very critical feature. 

Please note that I am not the original author nor the official maintainer. I am merely keeping this repo because I wanted to have some kind of a history and make sure the sources stay available, since I am still using elvis as my primary editor.

**Comment by TheLancashireman** [comment]
Hi Martin, thanks for the fix.
elvis is my primary programming editor too. I use vim when I need the unicode support (mainly for emails), but elvis has some features that I'm used to using when programming.
I'll pull the fix soon (probably tomorrow) and use it in a normal environment. I have lots of files at work with modelines in them, so I'll find out if it's OK there. They don't use ! commands though - I use modelines mainly for setting tab stops :-)

Cheers,
Dave

**Comment by ib** [comment]
@mbert

Sorry to butt in so late.

> The solution is simply filtering out any '!' from modeline lines before executing them.

If I'm not wrong, the '!'s are not filtered out, but modelines with '!'' are completely ignored now (which is okay, though).

But, doesn't the patch have a regression?

Since elvis' substitution is greedy, the content of the line was previously executed up to the last ':'. Everything behind that was ignored. After the patch, the modeline may only contain spaces after the last ':' or it is ignored, even if not containing any '!'s.

Attached is a patch ready for "git am" to correct this.

[correction.zip](https://github.com/mbert/elvis/files/4688399/correction.zip)

**Comment by mbert** [comment]
> @mbert
> 
> Sorry to butt in so late.
> 
> > The solution is simply filtering out any '!' from modeline lines before executing them.
> 
> If I'm not wrong, the '!'s are not filtered out, but modelines with '!'' are completely ignored now (which is okay, though).
> 
> But, doesn't the patch have a regression?
> 
> Since elvis' substitution is greedy, the content of the line was previously executed up to the last ':'. Everything behind that was ignored. After the patch, the modeline may only contain spaces after the last ':' or it is ignored, even if not containing any '!'s.
> 
> Attached is a patch ready for "git am" to correct this.
> 
> [correction.zip](https://github.com/mbert/elvis/files/4688399/correction.zip)

Thank you. Please bear with me for another while. This has been so completely out of context for me for quite some time, so that I will really need some time to get back into it and try to understand the issue you are seeing. I'll have to leave this in my inbox for another while though.

**Comment by dodona2** [comment]
caution!

**Comment by mbert** [comment]
OK, that was quicker than I thought. Thank you, @ib, looks like you're absolutely right. I have applied your patch. Not sure whether this requires a `pre4` version, I'll just leave it for those interested to git-pull for now.
