### ISSUE TITLE
Is this repo still active ?

### ISSUE THREAD

**Issue by OTonGitHub** [mbert/elvis#47]
I wanted to know if it is possible still contribute to this repo. I know Neovim has now taken over vim which took over vi.
But, this project still seems quite attractive, especially for educational purposes and something might come out of this. I am looking for a good C repo to contributing, this one is on the top of the list
BTW, I apologise if 'issues' is not the right place to ask questions like this, do let me know another way to do so if this is not the correct way so I will do that next time.
Also, have the project file structure changed majorly in this project, from the original elvis codebase?
Kind Regards, Have a nice day y'all.

**Comment by mbert** [comment]
Hi, I - though not being the original author - still more or less actively maintain this repo. I use Elvis every day. However its main shortcoming is the lack of Unicode support, and building this in would be a major undertaking (I am not familiar enough with termcap programming to do this). 

The repo follows the original source tar balls. Its first commits are actually imports of all the releases I could get hold of. After the last version released by Steve, I now use the repo in order to collect bugfixes where necessary and to have the code available for myself and others. 

Because the code is old and quite Unix-centric I do not think that it qualifies as a playground for learning. But if you have something useful to contribute, go ahead.
